name: Update File Count

on:
  push:
    paths:
      - 'indiv_solutions/**'  # Only run when files in 'indiv_solutions/' change
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count files in folder
        id: filecount
        run: |
          count=$(find indiv_solutions -name "*.py" | wc -l)
          echo "file_count=$count" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          count=${{ steps.filecount.outputs.file_count }}
          ps=2.99
          percentage=$(echo "scale=0; $count / $ps" | bc)
          sed -i '/<!-- FILECOUNT -->/c\!['"$count"'/'"$ps"'](https://progress-bar.xyz/'"$percentage"'?title='"$count"'/'"$ps"')<!-- FILECOUNT -->' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update progress in README" || echo "No changes to commit"
          git push
